version: '3.8'

services:
  # Traefik (Ingress Controller)
  traefik:
    image: traefik:v2.10
    command:
      - --api.insecure=true          # เปิด Dashboard (ใช้ชั่วคราว)
      - --providers.docker=true      # ใช้ Docker เป็น Provider
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
    ports:
      - "80:80"                     # HTTP
      - "443:443"                    # HTTPS
      - "8080:8080"                 # Traefik Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # ให้ Traefik ดู Docker Containers

  # ตัวอย่าง Service 1 (Web App)
  webapp:
    build: ./webapp
    labels:
      - "traefik.enable=true"                           # เปิดใช้งาน Traefik
      - "traefik.http.routers.webapp.rule=(Host(`www.farmingrobotic.com`) && PathPrefix(`/`))"  # ใช้โดเมนนี้
      - "traefik.http.routers.webapp.entrypoints=web"   # ใช้พอร์ต 80
    networks:
      - proxyrv_default  # ใช้ network เดียวกับ Traefik

  # ตัวอย่าง Service 2 (web2)
  webappapp:
    build: ./webappapp
    volumes:
      - ./webappapp/src:/usr/share/nginx/html  # สำหรับ Nginx แก้ หน้าเว็ปไม่เปลี่ย แคสค้าง
    # image: my-api:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webappapp.rule=(Host(`www.farmingrobotic.com`) && PathPrefix(`/web`))"
      - "traefik.http.routers.webappapp.entrypoints=web"
      - "traefik.http.services.webappapp.loadbalancer.server.port=80"
      - "traefik.http.middlewares.webappapp-stripprefix.stripprefix.prefixes=/web"
      - "traefik.http.routers.webappapp.middlewares=webappapp-stripprefix"
    networks:
      - proxyrv_default  # ใช้ network เดียวกับ Traefik

      # ตัวอย่าง Service 3 (API)
  myweb:
    image: mcr.microsoft.com/dotnet/samples:aspnetapp
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.myweb.rule=(Host(`www.farmingrobotic.com`) && PathPrefix(`/api`))"
      - "traefik.http.routers.myweb.entrypoints=web"
      - "traefik.http.services.myweb.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.myweb-stripprefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.myweb.middlewares=myweb-stripprefix"
    networks:
      - proxyrv_default  # ใช้ network เดียวกับ Traefik
    expose:
      - 8080

networks:
  proxyrv_default:
    external: true