
services:
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - web-app  # ต้องมีบรรทัดนี้
    networks:
      - proxy-network

  web-app:
    build: ./webapp
    ports:
      - "3000:80"  # เปิดเผยพอร์ตสำหรับทดสอบโดยตรง
    networks:
      - proxy-network
    environment:
      - NGINX_PORT=80

networks:
  proxy-network:
    driver: bridge