
services:
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web-app  # ต้องมีบรรทัดนี้
    networks:
      - proxy-network

  web-app:
    build: ./webapp
    expose:
      - "80"  # เปิดเฉพาะภายใน Docker network
    networks:
      - proxy-network
    environment:
      - NGINX_PORT=80

networks:
  proxy-network:
    driver: bridge

volumes:
  ssl: