version: '3.8'

services:
  traefik:
    image: traefik:v2.10
    command:
      - --api.insecure=true
      - --providers.docker.swarmMode=true
      - --providers.docker.network=traefik-public
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80  # ใช้แค่พอร์ต 80
    ports:
      - "80:80"  # เปิดแค่พอร์ต 80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true