version: '3.8'

services:
  web:
    image: nginx
    deploy:
      replicas: 3
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.web.rule=Host(`yourdomain.com`)"
        - "traefik.http.routers.web.entrypoints=websecure"
        - "traefik.http.routers.web.tls.certresolver=myresolver"
        - "traefik.http.services.web.loadbalancer.server.port=80"
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true