version: '3.8'

services:
  web:
    image: nginx
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.web.rule=(Host(`www.farmingrobotic.com`) && PathPrefix(`/`))"  # ใช้โดเมนนี้
        - "traefik.http.routers.web.entrypoints=web"  # เปลี่ยนจาก websecure เป็น web
        - "traefik.http.services.web.loadbalancer.server.port=80"
    networks:
      - traefik-public
 
  
  webapp:
    build: ./webappapp
    image: farmingrobotic/webapp:latest  # ควรตั้งชื่อ image ที่ชัดเจน
    volumes:
      - ./webappapp/src:/usr/share/nginx/html  # สำหรับ Nginx แก้ หน้าเว็ปไม่เปลี่ย แคสค้าง
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.webapp.rule=(Host(`www.farmingrobotic.com`) && PathPrefix(`/web`))"
        - "traefik.http.middlewares.webapp-stripprefix.stripprefix.prefixes=/web"
        - "traefik.http.routers.webapp.middlewares=webapp-stripprefix"
        - "traefik.http.routers.webapp.entrypoints=web"  # เปลี่ยนจาก websecure เป็น web
        - "traefik.http.services.webapp.loadbalancer.server.port=80"
      restart_policy:
        condition: on-failure
    networks:
      - traefik-public

  webapi:
    build: ./webapi
    image: farmingrobotic/webapi:latest  # ควรตั้งชื่อ image ที่ชัดเจน
    environment:
      - ASPNETCORE_ENVIRONMENT=Production  # เปลี่ยนจาก Development เป็น Production
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.webapi.rule=(Host(`www.farmingrobotic.com`) && PathPrefix(`/api`))"
        - "traefik.http.middlewares.webapi-stripprefix.stripprefix.prefixes=/api"
        - "traefik.http.routers.webapi.middlewares=webapi-stripprefix"
        - "traefik.http.routers.webapi.entrypoints=web"  # เปลี่ยนจาก websecure เป็น web
        - "traefik.http.services.webapi.loadbalancer.server.port=80"
      restart_policy:
        condition: on-failure
    networks:
      - traefik-public
 
networks:
  traefik-public:
    external: true