version: '3.8'

services:
  web:
    image: nginx
    deploy:
      replicas: 3
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.web.rule=Host(`www.farmingrobotic.com`)"
        - "traefik.http.routers.web.entrypoints=web"  # เปลี่ยนจาก websecure เป็น web
        - "traefik.http.services.web.loadbalancer.server.port=80"
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true